# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bc50913c872260630cd88af1a983e62006102432e5fec82412cb7075874349d464bb8e74d9cc3103b0dee17d253bf97ab761f54369b908ef477db6b1b59d2c01

test:
  secret_key_base: 0fde49598821810e90eca5c1f174ca977055a86fa2a1c09fe38772cb95ccabe783fc5dedac39a11ec0f950976f8840a9e4b7bff2f1406cd176feb07ef6c12058

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
